version: '3'

services:
  service-api:
    build: .
    container_name: service-api
    command: npm run start:debug
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    volumes:
      - .:/home/node/app
    networks:
      - rede-api

networks:
  rede-api:
